{{- range .Values.eventsEnclaveProcessor.instances }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Chart.Name }}-events-enclave-proc-{{ .name }}
  labels:
    app: {{ $.Chart.Name }}-events-enclave-proc-{{ .name }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ $.Chart.Name }}-events-enclave-proc-{{ .name }}
  template:
    metadata:
      labels:
        app: {{ $.Chart.Name }}-events-enclave-proc-{{ .name }}
    spec:
      serviceAccountName: raise-data
      containers:
        - name: {{ $.Chart.Name }}-events-enclave-proc-{{ .name }}
          image: {{ $.Values.eventsEnclaveProcessor.image.name }}:{{ $.Values.eventsEnclaveProcessor.image.tag }}
          imagePullPolicy: Always
          command: ["events-enclave-processor"]
          args: ["--daemonize"]
          env:
            - name: SQS_QUEUE
              value: {{ .sqsQueue }}
            - name: POLL_INTERVAL_MINS
              value: "{{ .pollIntervalMins }}"
            - name: JSON_OUTPUT_S3_BUCKET
              value: {{ .jsonOutputS3Bucket }}
            - name: JSON_OUTPUT_S3_KEY
              value: {{ .jsonOutputS3Key }}
{{- end }}