"""Update course table with district metadata

Revision ID: 08490e32191c
Revises: 0f2ac8029e38
Create Date: 2023-08-17 15:11:52.623135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08490e32191c'
down_revision = '0f2ac8029e38'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('district', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'district')
    # ### end Alembic commands ###
