"""Test without visible column

Revision ID: 43ad9fc768a4
Revises: 8748834e91a6
Create Date: 2023-08-09 15:04:50.698916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43ad9fc768a4'
down_revision = '8748834e91a6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Uuid(), nullable=False),
    sa.Column('term', sa.String(), nullable=False),
    sa.Column('section', sa.String(), nullable=False),
    sa.Column('activity_name', sa.String(), nullable=False),
    sa.Column('lesson_page', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_id', 'term')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_content')
    # ### end Alembic commands ###
