"""Update course table with district metadata

Revision ID: e77f74d9e07a
Revises: 0f2ac8029e38
Create Date: 2023-08-15 12:02:48.992754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e77f74d9e07a'
down_revision = '0f2ac8029e38'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('district', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'district')
    # ### end Alembic commands ###
