version: 0.2

env:
  shell: bash
  secrets-manager:
    SLACK_WEBHOOKURL: "slack:k12stream"
    DASHBOARD_POSTGRES_USER: "rds-raise-dashboard:username"
    DASHBOARD_POSTGRES_PASSWORD: "rds-raise-dashboard:password"

phases:
  install:
    commands:
      - curl -L https://get.helm.sh/helm-v3.15.3-linux-amd64.tar.gz | tar -xvz
      - mv linux-amd64/helm ./helm
      - curl -L -o yq "https://github.com/mikefarah/yq/releases/download/v4.44.2/yq_linux_amd64"
      - chmod +x ./helm ./yq
      - export PATH=$PWD:$PATH
  pre_build:
    commands:
      - aws eks update-kubeconfig --name $K8S_CLUSTER_NAME
      - export DATA_IMAGE_NAME=$(cat $CODEBUILD_SRC_DIR_data_build_output/data-image-name.txt)
      - export DATA_IMAGE_TAG=$(cat $CODEBUILD_SRC_DIR_data_build_output/data-image-tag.txt)
      - touch ./values.yaml
      - yq e -i '.eventsEnclaveProcessor.image.name=strenv(DATA_IMAGE_NAME)' ./values.yaml
      - yq e -i '.eventsEnclaveProcessor.image.tag=strenv(DATA_IMAGE_TAG)' ./values.yaml
      - yq e -i '.moodleDashboardProcessor.image.name=strenv(DATA_IMAGE_NAME)' ./values.yaml
      - yq e -i '.moodleDashboardProcessor.image.tag=strenv(DATA_IMAGE_TAG)' ./values.yaml
      - yq e -i '.eventsDashboardProcessor.image.name=strenv(DATA_IMAGE_NAME)' ./values.yaml
      - yq e -i '.eventsDashboardProcessor.image.tag=strenv(DATA_IMAGE_TAG)' ./values.yaml
      - yq e -i '.dashboard.pgUsername=strenv(DASHBOARD_POSTGRES_USER)' ./values.yaml
      - yq e -i '.dashboard.pgPassword=strenv(DASHBOARD_POSTGRES_PASSWORD)' ./values.yaml
      - yq e -i '.dashboard.pgServer=strenv(DASHBOARD_POSTGRES_SERVER)' ./values.yaml
  build:
    commands:
      - helm upgrade -n raise --install -f ./values.yaml raise-data deploy/chart/
      - export SLACK_MESSAGE="raise-data deployment completed successfully for commit $COMMIT_ID"
      - "curl -X POST -H 'Content-type: application/json' --data '{\"text\":\"'\"$SLACK_MESSAGE\"'\"}' $SLACK_WEBHOOKURL"
