---
name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: pip install .[test]
      - name: Lint
        run: flake8
      - name: Test setup
        working-directory: dashboard
        run: |
          docker compose up -d postgres
          docker compose exec -T postgres timeout 10 bash -c "until pg_isready; do sleep 1; done;"
          docker compose exec -T postgres psql -U pguser postgres -c "CREATE DATABASE raisemetrics"
          alembic upgrade head
      - name: Test
        run: pytest --cov-report=term --cov-report=xml --cov=raise_data
      - name: Upload Code Coverage
        uses: codecov/codecov-action@v3
