---
name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: |
          pip install flake8 pytest pytest-cov pytest-mock
          pip install -r events-enclave-processor/requirements.txt
          pip install -r events-loader/requirements.txt
      - name: Lint
        run: flake8
      - name: Test
        run: pytest --cov-report=term --cov-report=xml --cov
      - name: Upload Code Coverage
        uses: codecov/codecov-action@v2
